/*
 * This source file was generated by the Gradle 'init' task
 */
package at.neon;

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.BeforeEach

class NeonLibraryTest {

    private lateinit var sut: NeonLibrary

    @BeforeEach
    fun setUp() {
        this.sut = NeonLibrary()
    }

    @Test
    fun someLibraryMethodReturnsTrue() {
        val rand = sut.getRandomNumber()
        assertTrue(rand >= 0 && rand < 1.0)
    }
}
